[package]
name = "adventofcode_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = "4.4.10"
regex = "1.10.2"
rstest = "0.18.2"
num = "0.4.1"
colored = "2.1.0"
